### ISSUE TITLE
No Such Module YouTubePlayer

### ISSUE THREAD

**Issue by prshnt** [gilesvangruisen/Swift-YouTube-Player#29] opened 2015-07-20 06:11 UTC
I used CocoaPods to use your project however when I try to use it using 

import YouTubePlayer

I get the error saying No Such Modue YouTubePlayer. I am on XCode 6.4

**Comment by gilesvangruisen** [comment] 2015-07-23 04:27
Hi @prshnt. This is a duplicate of #2 and is usually due to something going wrong during the installation process. I'm able to create a new project and import the library using Cocoapods just fine, so I'm going to close this issue.

Please check out the [README](https://github.com/gilesvangruisen/Swift-YouTube-Player/blob/master/README.md) and follow the instructions carefully. If you're still having trouble, please provide the repository in question and I'll do my best to investigate.

**Closed by gilesvangruisen** 2015-07-23 04:27 UTC

**Comment by marcus-grant** [comment] 2016-07-17 23:31
I followed the instructions to the letter. Make my Xcode project that will use your pod, close xcode, direct terminal to root directory containing the XCode project, pod init, added "pod 'YouTubePlayer'" after the use_frameworks! line, pod install, open the newly created workspace containing the old project. I've read every similar post and don't see any help on what could possibly be going wrong with my pod install process. I still get red framework references in the project explorer, and when I go to "import YouTubePlayer" it is still unrecognized.

**Comment by gilesvangruisen** [comment] 2016-07-17 23:48
hi @marcus-grant! sorry you're having trouble :(

one common mixup with CocoaPods is opening the `.xcodeproj` instead of the `.xcworkspace` file to open the project in Xcode. The `.xcodeproj` will only contain your project-related files and won't be linked with your dependencies. The `.xcworkspace` will contain both your `.xcodeproj` and another `.xcodeproj` used for dependencies that Cocoapods generates.

Are you sure you're opening the `.xcworkspace` when you try to run your project?

**Comment by marcus-grant** [comment] 2016-07-18 00:03
Thanks for fast response! Nope, I'm using the .xcworkspace, and usually I'm opening it directly from the command line with open *.xcw* as the command, but I've also tried from "Open Workspace" menu within xcode. This is what the workspace looks like
<img width="1272" alt="screen shot 2016-07-17 at 7 58 58 pm" src="https://cloud.githubusercontent.com/assets/12179903/16903918/4122df98-4c59-11e6-98ee-2414625efb41.png">
<img width="1264" alt="screen shot 2016-07-17 at 7 58 37 pm" src="https://cloud.githubusercontent.com/assets/12179903/16903919/47709930-4c59-11e6-8463-eb5823715fc3.png">

And this is my podfile, and where it's stored relative to the xcode workspace and projects
<img width="625" alt="screen shot 2016-07-17 at 7 57 20 pm" src="https://cloud.githubusercontent.com/assets/12179903/16903930/78839d4c-4c59-11e6-80d5-8b7122bbc0e4.png">
<img width="632" alt="screen shot 2016-07-17 at 7 58 04 pm" src="https://cloud.githubusercontent.com/assets/12179903/16903932/84449c8a-4c59-11e6-8496-1a380f241445.png">
