### ISSUE TITLE
Update from UIWebView to WKWebView

### ISSUE THREAD

**Issue by anonym24** [gilesvangruisen/Swift-YouTube-Player#181] opened 2019-03-08 15:04 UTC
So `UIWebView` isn't supported anymore

> 'UIWebView' was deprecated in iOS 12.0: No longer supported; please adopt WKWebView.

**Comment by weakfl** [comment] 2019-03-28 12:13
dupe of #172 and there's also a PR (#173) waiting to be merged...

**Closed** 2019-03-29 15:29 UTC
